sudo: false
language: ruby

jobs:
  include:
    - stage: test
      before_install: gem install bundler -v 1.17.1
      cache: bundler
      rvm:
        - 2.4.5
        - 2.5.3
        - 2.6.0-rc1
    - stage: deploy
      before_install: gem install bundler -v 1.17.1
      script: skip
      deploy:
        provider: rubygems
        api_key:
          secure: "VvcCu3nHImRHjl5BFOAui4kT5bmwA13WFPe4svkG44cFMKxYh4XxGi2xCdoPvwaZiMQ5BfFaoH4B1Z0v/tOa31UTLnS0IIaN51mtKKjLJMv7FiVliliGOPLyAzSpM88psrXGiYTzLC20UiQWUIHT9al4Rh2a9tNZ5D2DFIs0PnupGVCIpLVYqeT2GqOEj886GNCW4+VFT+PblI+140gMrLwj0Z+G5DhwPsvNtG6Z8L31w+xQyzBYnyWYxEZnoZTnn4zTwyqWv65Pse9fWbxca6rGYfpFyhAhvN+TLzWmF4sHvRJx8U9RxixCk1QX6xaaVMh+O7CpKs4hl1D8EeME5miB/Sj2VWdbiv57DOKMieEI1ZxqUj5QqpLNWa546CU9p/rNPTXBbIPXNaZq3MY09cLdu4iFxgbDNdUt+Y5O5a19U2dDh8+dTIRrmNrXXSXseqJbH5g58HHcJ3hta00KZveBMUOyUVreRCVQNgNMlVwp7IMwEb/upT7Dzonn80mLsP+4FEPTjlg1oIbYWuNJUg6tyVx/uuQbggrAhiWhxfvrKTa4t6da46qPI7MrQ+/z2gu6Zy+POhxBAiETVAvwIlgUPZga1eDWNp07WmHXaimy+sXaZeS1QalBf3A2+VACy8guKzj6e5J/EuNnI+NaNgErHPqW9l/6yVkZhYFYR0w="
        gem: rspec_enhanced_json_formatter
        on:
          tags: true
          repo: uniite/rspec_enhanced_json_formatter
